kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # Add zones due to the issue https://github.com/kubernetes/kubernetes/issues/39178
  zone: us-east-1b
