apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: python:2
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]

